slug: gql
landscapeMemberClasses:
   - name: General Membership
     category: General
landscapeMemberCategory: GraphQL Foundation Member
memberSuffix: " (member)"
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/graphql-foundation
