landscapeName: graphql
landscapeMemberClasses:
   - name: General Membership
     category: General
project: a092M00001G4R8CQAV # GraphQL Foundation
landscapeMemberCategory: GraphQL Foundation Member
landscapefile: landscape.yml
defaultCrunchbase: https://www.crunchbase.com/organization/graphql-foundation
missingcsvfile: missing.csv
memberSuffix: " (member)"
